.TH "OPY" 1 "2019-11-9" "Man Page" "Utility Commands"

.SH NAME
opy \- onelinerers' Python

.SH SYNOPSIS
.B opy
[
.BI \-bcCs
]
[
.BI \-i
.I separators
|
.BI \-I
.I separators
]
[
.BI \-m 
.I modules
]
[
.BI \-o
.I separators
]
[
.BI \-v
.I <variable>=<string>
]
.I 'prog'
[
.I file ...
]

.SH DESCRIPTION
.PP
.I Opy
reads each line of each
.I file
and reacts based on the rules written in the 
.I prog. 

.SH OPTIONS
.TP
.B \-b
buffer the standard output
.TP
.B \-c
read data as UTF-8 CSVs
.TP
.B \-C
output data as UTF-8 CSVs
.TP
.B \-s
treat numbers from input data as strings
.TP
.B \-i
.I separators
change input field separators
.TP
.B \-I
.I separators
change input field separators with a regular expression
.TP
.B \-m
.I modules
import modules 
.TP
.B \-o
.I separators
change output field separators
.TP
.B \-v
.I <variable>=<string>
define a variable from a string on the shell
.TP
.B \-t <json|yaml|xml>
tree mode. Opy reads a tree from a file and it is stored to an object T.

.SH SEE ALSO
.BR python3 (1)
