name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up and test with Python ${{ matrix.python-version }}
      run: |
        sudo apt-get install python3-pip bats
        pip3 install numpy pandas
        ./test
